In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("TRAIN_ver02.csv")

In [3]:
data

,LID,CHNL,SELLER,ORIGRATE,ORIGUPB,ORIGTERM,LOANAGE,REMMNTHS,ADJRMTHS,OLTV,...,MSA,ZIP,DLQSTATUS,RELMORTGIND,ACTPER_MO,GAP,TIMGAP1,TIMGAP2,NMONTHS,FORCLOSED
0,946681740815,B,"Jpmorgan Chase Bank, National Association",8.000,100000.0,360,1,359,359,51.0,...,12060,300,0,N,4,False,2,359,17,False
1,921089628109,R,"Gmac Mortgage, Llc",7.625,100000.0,180,0,180,180,80.0,...,12540,932,0,N,4,False,2,179,32,False
2,738779422112,C,"Flagstar Bank, Fsb",8.000,226000.0,180,1,179,178,80.0,...,42660,981,0,N,4,False,2,179,19,False
3,615798070845,R,Other,8.205,143000.0,360,0,360,360,77.0,...,42140,875,0,N,3,True,2,359,21,False
4,345601060557,R,Other,8.500,46000.0,360,0,360,360,80.0,...,41180,622,0,N,3,True,2,359,17,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188737,562335400010,R,"Bank Of America, N.A.",8.250,96000.0,360,0,360,360,80.0,...,46060,857,0,N,3,True,2,359,14,False
188738,151011432193,C,Suntrust Mortgage Inc.,8.875,86000.0,360,0,360,360,59.0,...,19820,483,0,N,3,False,2,359,23,False
188739,517753415065,R,Bishops Gate Residential Mortgage Trust,8.500,70000.0,360,0,360,359,64.0,...,37980,80,0,N,5,False,2,359,17,False
188740,948158851357,R,"Jpmorgan Chase Bank, Na",8.250,61000.0,180,0,180,177,70.0,...,31700,30,0,N,5,False,2,179,40,False
188741,603343045348,C,"Flagstar Bank, Fsb",7.875,97000.0,360,0,360,358,90.0,...,0,983,0,N,5,False,2,359,29,False